# Generated by Django 4.1.1 on 2022-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('sensor_type', models.CharField(max_length=30)),
                ('reading', models.IntegerField()),
            ],
        ),
    ]
