version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
    ports:
      - "8888:5432"
